name: CI/CD Actividad 6.1

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Inicio de sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Construcción y subida de la imagen (BUILD & PUSH)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: erickamasonense/actividad61-aplicacion-crud-php:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue en Servidor de Producción (PULL & RUN)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/actividad61-aplicacion-php-produccion-
            git pull origin main
            docker compose down -v
            docker compose pull www 
            docker compose up -d
